### ISSUE TITLE
[v3] Use Host SSHKEY for SFTP auth

### ISSUE THREAD

**Issue by Merith-TK** [satisfactorymodding/SatisfactoryModManager#204]
So my server has password authentication turned off for security in favor of sshkey authentication.

Except, the mod manager does not use sshkey authentication, if I were to use winscp or filezilla they use my sshkey for sftp

**Comment by Merith-TK** [comment]
Would like to give an update to this
*because* I was forced to lower security on my server just to use this feature. Someone was able to compromise my server with a bot net, 

This is a genuine security issue for those unprepared on how to handle this, as the current recommended sftp docker container I was planning on using, simply *refuses* to work at all.

**Comment by budak7273** [comment]
context: https://discord.com/channels/555424930502541343/555516979260293132/1254472957695365162

**Comment by Merith-TK** [comment]
Current solution (note, the docker container for SFTP has been finicky for me)
```yml
# docker-compose
services:
  server:
    image: wolveix/satisfactory-server:latest
    container_name: satisfactory-server
    hostname: satisfactory-server
    restart: "unless-stopped"
    volumes:
      - ./server:/config
      - ./.steamcmd/home/.steam:/home/steam/.steam/
      - ./.steamcmd/home/Steam:/home/steam/Steam/
    environment:
      MAXPLAYERS: 10
      AUTOPAUSE: "false"
      # make sure this matches the UID for SFTP
      PGID: 1001
      PUID: 1001

    deploy:
      ## Not needed, this just helps limit
      resources:
        reservations:
          memory: 8G
        limits:
          memory: 10G
    ports:
      - 7777:7777/udp
      - 15000:15000/udp
      - 15777:15777/udp

  sftp:
    image: atmoz/sftp
    ulimits: # this fixes issues
      nofile:
        soft: "5120"
        hard: "5120"
    volumes:
        - ./:/home/game/
    ports:
        - "222:22"
    command: user:pass:1001 # again, make sure this number matches above
    ```
